name: mikan
description: mikanani.me

version: 1.2.4+70

publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_analytics: ^10.10.2
  firebase_crashlytics: ^3.5.2
  path_provider: ^2.1.1
  dio: ^5.1.2
  dio_cookie_manager: ^3.0.0
  html: ^0.15.3
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  clipboard: ^0.1.3
  url_launcher: ^6.1.14
  share_plus: ^7.0.1
  flutter_widget_from_html_core: ^0.14.11
  extended_sliver: ^2.1.3
  waterfall_flow: ^3.0.2
  jiffy: ^6.1.0
  android_intent_plus: ^4.0.0
  connectivity_plus: ^4.0.0
  ff_annotation_route_core: ^2.0.7
  ff_annotation_route_library: ^3.0.0
  sliver_tools: ^0.2.10
  flutter_displaymode: ^0.6.0
  flex_color_picker: ^3.2.2
  intl: ^0.18.1
  collection: ^1.17.0
  json_annotation: ^4.8.1
  path: ^1.8.2
  cookie_jar: ^4.0.2
  async: ^2.10.0
  auto_size_text: ^3.0.0
  easy_refresh: ^3.3.2+1
  window_manager: ^0.3.6
  dynamic_color: ^1.6.7
  decimal: ^2.3.2
  flutter_smart_dialog: ^4.9.4
  infinite_carousel: ^1.0.3
  package_info_plus: ^4.1.0
  animations: ^2.0.8
  vclibs: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  args: ^2.4.1
  yaml: ^3.1.2
  glob: ^2.1.1
  http: ^1.1.0
  process_run: ^0.13.0
  build_runner: ^2.3.3
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.6.2
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.3
  icons_launcher: ^2.1.0
  quiver: ^3.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/res/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

icons_launcher:
  image_path: 'assets/mikan.png'
  platforms:
    android:
      enable: false
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

